### ISSUE TITLE
multiviewer

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#10]
It is not possible to select more than 16 epochs at the same time without getting an error
Error using axes
Width and height must be > 0

Error in subplot (line 515)
            ax = axes('Units', 'normalized', 'Position', position, ...

Error in subaxis (line 88)
    h=subplot('position',[xpos1 1-ypos2 xpos2-xpos1 ypos2-ypos1]);

Error in CGLW_multi_viewer>update_graph (line 221)
            currentaxis(row_pos,col_pos)=subaxis(num_rows,num_cols,graph_pos,'MarginLeft',0.06,'MarginRight',0.02,'MarginTop',0.04,'MarginBottom',0.08,'SpacingHoriz',0.06,'SpacingVert',0.06);
            
Error in CGLW_multi_viewer>epoch_listbox_Callback (line 542)
update_graph(handles);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in CGLW_multi_viewer (line 24)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)CGLW_multi_viewer('epoch_listbox_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uicontrol Callback

**Comment by amouraux** [comment]
I believe that this limitation is only when you want to plot the 16 waveforms in separate graphs.
