### ISSUE TITLE
Change to GLW_event_browser for fewer than 3 events

### ISSUE THREAD

**Issue by AlexWoolgar** [NOCIONS/letswave6#105]
Hi folks, thanks very much for the fantastic software!

I noticed a problem in GLW_event_browser.m. In my data I only have one event, so my events variable has fewer rows than columns. GLW_event_browser crashes on line 473, because it tries to read out a third row. The following change fixes it (from line 472):

for i=1:size(tp,1); % AW 3/8/2016, needs to be size(tp,1) not length(tp) to cope with having less than two rows in events variable
     events(i).code=tp{i,1};
     events(i).epoch=tp{i,2};
     events(i).latency=tp{i,3};
end;

I also had an issue with the 'update events list' button with the error "Subscripted assignment between dissimilar structures" line 380, which I fixed by switching the order so that event.epoch is defined before event.latency (as below, from line 376). I'm not sure if that issue is specific to my version of MATLAB or something, but in case it's relevant, I'm using 2014a.

for i=1:size(table_data,1);
    event.code=table_data{i,1};
    event.epoch=fix(str2num(table_data{i,2})); % AW 3/8/16 switched order here to make structures match (MATLAB 2014a)
    event.latency=str2num(table_data{i,3});
    header.events(end+1)=event;
end;

I hope this is an appropriate way to report an issue, I've never used github before!

Thanks again,
Alex

**Comment by amouraux** [comment]
Thanks! I just updated the file on Github!
