### ISSUE TITLE
compute area under the curve

### ISSUE THREAD

**Issue by giulia92222** [NOCIONS/letswave6#109]
Dear all,

I'm using letswave6 with EEG files and I would like to know how I can compute the area under the curve, maybe is it something related to the section "multiviewer"? I found the function "find peaks" (min and max) but I would need more informations about computing areas...

Thank you so much

**Comment by amouraux** [comment]
You should be able to do this in the “Explore ROI” function.
Can you get back to me if this does not work?

Kind regards,
André

**Comment by giulia92222** [comment]
Dear Prof. Mouraux

thank you very much for your answer.

Unfortunately I don't find the function. I found the function "generate table and graphs 
with ROI" under "View" menu, but there is no the "area under the curve information".
Am I wrong?

In LW4 I obtained the Area under the Curve right clicking on the wa4 file:
"explore - waves, extract information"

Thanks again,

Giulia Guerra

**Comment by valebrown** [comment]
Dear Giulia, 
I have your same problem. Did you understand where to find the "Explore ROI" function?

Thank you, 
Valentina

**Comment by amouraux** [comment]
Sorry. The function is actually called "Generate table and graphs with ROI data" in the View menu.
I have now added the AUC calculation, which will appear as an additional column when you click "Generate Table".

**Comment by valebrown** [comment]
Dear Prof. Mouraux, 
thank you very much, it perfectly works.

Kind regards,
