### ISSUE TITLE
Import VHDR

### ISSUE THREAD

**Issue by Manolo68** [NOCIONS/letswave6#112]
Hi,
When I try do import signal and click on "import brainvision vhdr files", the window opens but with a strange format and I can't choose the folder where my files are. Even if I try to maximize the window or else, I cannot do nothing and even the buttoon "process" is almost invisible. It looks like a graphic bug but could not figure it out. Even more annoying, it worked perfectly the last time I used letswave 6 so can't really understand what happened.
Anyone had the same problem or knows how to fix it ? 

thanks for your help,
best.
Manu

**Comment by rachelrhs20** [comment]
Hi, 
Same problem here, would be grateful for a fix if anyone knows of one.
Thank you for your help.
Rachel

**Comment by MegaCurry** [comment]
Hi,
I am also faced with the same problem with you guys. Not only when "import vhdr files", but also in "import ASCII". It seems a GUI problem. I searched the net but found it's hard to change the options by scripts.

Thank you for your help
Moqian

**Comment by amouraux** [comment]
This should now be fixed after you update.
