### ISSUE TITLE
Problems with “Merge channels from different datasets”

### ISSUE THREAD

**Issue by mmvar** [NOCIONS/letswave6#113]
Dear Andre, 

Thanks for the toolbox! I started using it recently but already like it very much. However, I cannot use “Merge channels from different datasets”. I always get the following error:  

_Subscripted assignment between dissimilar structures.

Error in RLW_merge_channels (line 116)
            out_header.chanlocs(i)=tp3;

Error in LW_merge_channels (line 77)
        [out_datasets.header,out_datasets.data,message_string]=RLW_merge_channels(datasets,configuration.parameters.merge_idx);

Error in letswave_gui>menu_callback (line 387)
                [configuration,datasets]=eval(eval_st);

Error while evaluating Menu Callback_

I am using Letswave6 with Matlab 2015a on MacOS Sierra. Any suggestion would be very appreciated. Thanks! 

Manuel

**Comment by amouraux** [comment]
Bug has now been fixed! Sorry for the delay.
