### ISSUE TITLE
Can't import BrainVision VHDR files

### ISSUE THREAD

**Issue by rachelrhs20** [NOCIONS/letswave6#118]
When I do File>Import signals>Import BrainVision VHDR files, the dialog box for file selection pops up at the wrong size. 
I can see only a corner of the box, it will not resize, and therefore it is not possible to select files for import.
Any solutions gratefully received.
Thanks for your help.
Rachel

**Comment by amouraux** [comment]
Hello,

I should be able to fix this easily, probably tomorrow when I have access to a Windows machine.
It is a Mac/Windows problem when we edit the GUIs.
I thought that I had solved this previously, can you confirm that you have the latest version?

Best wishes,
André


On 29 Nov 2016, at 17:13, rachelrhs20 <notifications@github.com<mailto:notifications@github.com>> wrote:


When I do File>Import signals>Import BrainVision VHDR files, the dialog box for file selection pops up at the wrong size.
I can see only a corner of the box, it will not resize, and therefore it is not possible to select files for import.
Any solutions gratefully received.
Thanks for your help.
Rachel

**Comment by rachelrhs20** [comment]
Hi Andre

Thanks very much for your prompt response.

I downloaded the software today. The zip file is NOCIONS-letswave6-6.0-237-g4be7eca.zip and I got it from http://nocions.github.io/letswave6/

Now I see that both www.nocions.org/letswave<http://www.nocions.org/letswave> and https://github.com/NOCIONS/letswave6/wiki/Download-and-setup link to a file called master.zip

Shall I try that one before putting you to the trouble of (re-)fixing the problem?

Thanks again

Rachel
________________________________

**Comment by rachelrhs20** [comment]
Hello again Andre

The problem is still there when I use the letswave6-master.zip file, unfortunately.

sorry! and thank you

Rachel
________________________________

**Comment by amouraux** [comment]
I just fixed the visualisation glitch in all import functions. It should work fine after updating. Seems to be related to a weird behaviour of Matlab GUIs across platforms. Please tell me if you find any other function with such a visualisation problem.

**Comment by rachelrhs20** [comment]
Hi Andre
Thank you so much! Really appreciate this. I will let you know if I come across any other issues.
Best wishes
Rachel

Sent from my iPhone

On 1 Dec 2016, at 06:14, André Mouraux <notifications@github.com<mailto:notifications@github.com>> wrote:


I just fixed the visualisation glitch in all import functions. It should work fine after updating. Seems to be related to a weird behaviour of Matlab GUIs across platforms. Please tell me if you find any other function with such a visualisation problem.
