### ISSUE TITLE
Problems on GUIs of importing VHDR,EEGLAB set,Neuroscan eeg,LW4 MAT

### ISSUE THREAD

**Issue by MegaCurry** [NOCIONS/letswave6#119]
Hi,
Thanks a lot for your help. But some problems still exist after I have downloaded and installed the latest version"NOCIONS-letswave6-6.0-245-gc4f2deb.zip". Could you fix these problems(shown below)? Thank you so much!

![image 7](https://cloud.githubusercontent.com/assets/25113545/21973248/37a09024-dbfa-11e6-9643-b67d23ba0468.png)
![image 8](https://cloud.githubusercontent.com/assets/25113545/21973250/37a0f672-dbfa-11e6-935d-b797428ab17f.png)
![image 9](https://cloud.githubusercontent.com/assets/25113545/21973251/37d1fe66-dbfa-11e6-9e69-096df96ce9f7.png)
![image 10](https://cloud.githubusercontent.com/assets/25113545/21973247/379dfbca-dbfa-11e6-8f9a-3ab6027f6640.png)
![image 11](https://cloud.githubusercontent.com/assets/25113545/21973249/37a0b6f8-dbfa-11e6-826d-88b99ca800b3.png)

**Comment by amouraux** [comment]
Should be fixed now.
