### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by hughherald** [NOCIONS/letswave6#12]
![update_issue](https://cloud.githubusercontent.com/assets/7745431/7493418/f258e88c-f400-11e4-8405-d77f07393992.jpg)

When we try to update letswave, we receive this error message and you could notice that the new files are not properly located. (path problem)

Gan & Cedric.

**Comment by amouraux** [comment]
Finally understood why I could not replicate this problem on my computer. It is due to the fact that the folder where LW6 is installed has the same name as the temporary folder where the ZIP is unzipped. Trying to find a workaround.

**Comment by amouraux** [comment]
Fixed! Can you test it?

**Comment by amouraux** [comment]
You will have to manually update first of course...

**Comment by hughherald** [comment]
Yes, I tested it. everything fine!

Thanks.
