### ISSUE TITLE
Interpreting and plotting ANOVA results

### ISSUE THREAD

**Issue by cab79** [NOCIONS/letswave6#120]
Hi

This looks like great software. I'm mostly interested in using the statistics (ANOVA). I've run some stats with cluster permutation testing but I can't find any information regarding how to plot or interpret the results. Using the multiviewer I can see that there are 4 'epochs' (coming from the first dimension of the p-values matrix) which I judge from the code might be thresholded p values and cluster values. Still, I'm not clear on how to interpret these outputs. Is there some reference material I can read to find out about this? Also, is there a plotting function that will show when and where (on the scalp) the clusters are?

Many thanks
Chris

**Comment by amouraux** [comment]
Hello,

Indeed, the output has four "epochs", as follows: 
Epoch 1 = p or F values (depending on the file)
Epoch 2 = p or F values (within the clusters that survived the permutation testing)
Epoch 3 = percentile value of each cluster relative to the distribution of the cluster values obtained from the permutation testing (using all clusters for each permutation).
Epoch 4 = percentile value of each cluster relative to the distribution of the cluster values obtained from the permutation testing (using the max. cluster for each permutation).

The clusters shown in epoch 2 are thus only those whose percentile exceeded the 'Cluster Threshold' value set when running the function.
