### ISSUE TITLE
Reject epochs (visual inspection) 

### ISSUE THREAD

**Issue by HugotenDam** [NOCIONS/letswave6#121]
Hi dear people from letswave, 

When i try to inspect my data visually the window won't open in a normal way, not allowing me to select channels or properly inspect the data (see picture for how the window looks). I can't adjust the window by scrolling or sliding the scroll bar. 

![image](https://cloud.githubusercontent.com/assets/25753279/22900728/ae3c1442-f22f-11e6-8229-68e9bc933543.png)

**Comment by amouraux** [comment]
Hello.
Should be fixed now after updating.
This is really a weird bug, related to some compatibility issue between Mac and Windows.

Best wishes,
André

--
André Mouraux
Institute of Neuroscience (IONS)
Faculty of Medicine
University of Louvain
53, Avenue Mounier (B1.53.04)
B1200, Brussels, Belgium

Web: http://www.nocions.org
Tel : +32.2.764.5447



On 13 Feb 2017, at 21:03, HugotenDam <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi dear people from letswave,

When i try to inspect my data visually the window won't open in a normal way, not allowing me to select channels or properly inspect the data (see picture for how the window looks). I can't adjust the window by scrolling or sliding the scroll bar.

[image]<https://cloud.githubusercontent.com/assets/25753279/22900728/ae3c1442-f22f-11e6-8229-68e9bc933543.png>

**Comment by HugotenDam** [comment]
Hi Andre,

You are right. I downloaded the package again and now it works. However, i
can't manage to fill in the amplitude criterion upon visual inspection
(see picture). Do you know (once again) why?

Kind regards,

Hugo

[image: Inline afbeelding 1]

Met vriendelijke groet,

Hugo ten Dam

2017-02-15 15:13 GMT+01:00 André Mouraux <notifications@github.com>:

> Hello.
> Should be fixed now after updating.
> This is really a weird bug, related to some compatibility issue between
> Mac and Windows.
>
> Best wishes,
> André
>
> --
> André Mouraux
> Institute of Neuroscience (IONS)
> Faculty of Medicine
> University of Louvain
> 53, Avenue Mounier (B1.53.04)
> B1200, Brussels, Belgium
>
> Web: http://www.nocions.org
> Tel : +32.2.764.5447 <+32%202%20764%2054%2047>
>
>
>
> On 13 Feb 2017, at 21:03, HugotenDam <notifications@github.com<mailto:

**Comment by amouraux** [comment]
I cannot view the attached picture, and I am able to fill in the amplitude criterion on my own setup. Could you send the picture again?

Best wishes,
André

**Comment by HugotenDam** [comment]
Hi André,

Strange: I can open and view it.
Now I attached the image.

Kind regards,

Hugo ten Dam

Met vriendelijke groet,

Hugo ten Dam

2017-03-07 8:34 GMT+01:00 André Mouraux <notifications@github.com>:
