### ISSUE TITLE
Bug in Map Multiviewer figure

### ISSUE THREAD

**Issue by Manolo68** [NOCIONS/letswave6#128]
Dear,
I noticed that with the last update of LW6, I have a bug when I open the Map Multiviewer of an average or grand average (X and Y options are not visible anymore, the window of the MM is half cut)
Am I the only one ? Could you please fix this issue ? 

Thank you very much for your work !
Best,

manu

**Comment by mgrabo** [comment]
Hi Manu, 

I have the same problem. I am working with windows 10 and Matlab 2016b. It would be great if this issue could be fixed. 
Thank you very much for your work! 

Kind regards,
Martyna

**Comment by GiuliaL** [comment]
Hi, 
I have the same issue...

Giulia

**Comment by amouraux** [comment]
Very annoying Matlab bug causing Mac <> Windows display issues. Should be fixed now.
