### ISSUE TITLE
ANOVA failure with TF data

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#129]
Dear Andre', 

could you please check it out?

Error while evaluating Menu Callback

Error: File: ILW_custANOVA_parfor.m Line: 242 Column: 4
This statement is not inside any function.
 (It follows the END that terminates the definition of the function "ILW_custANOVA_parfor".)

Error in RLW_ANOVA (line 131)
    [out_dataset_pvalue,out_dataset_Fvalue]=ILW_custANOVA_parfor(datasets,within_levels,within_labels,between_levels,between_labels);

Error in LW_ANOVA (line 82)
        [out_datasets(1),out_datasets(2),message_string,cluster_distribution]=RLW_ANOVA(datasets,configuration.parameters.factor_data,configuration.parameters.table_data,'enable_parallel',configuration.parameters.enable_parallel,'alpha',configuration.parameters.alpha,'permutation',configuration.parameters.permutation,'num_permutations',configuration.parameters.num_permutations,'cluster_statistic',configuration.parameters.cluster_statistic,'cluster_threshold',configuration.parameters.cluster_threshold);
        
Error in letswave_gui>menu_callback (line 387)
                [configuration,datasets]=eval(eval_st);
 
Error while evaluating Menu Callback

**Comment by amouraux** [comment]
Fixed!
André



On 23 May 2017, at 19:29, EVale <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Andre',

could you please check it out?

Error while evaluating Menu Callback

Error: File: ILW_custANOVA_parfor.m Line: 242 Column: 4
This statement is not inside any function.
(It follows the END that terminates the definition of the function "ILW_custANOVA_parfor".)

Error in RLW_ANOVA (line 131)
[out_dataset_pvalue,out_dataset_Fvalue]=ILW_custANOVA_parfor(datasets,within_levels,within_labels,between_levels,between_labels);

Error in LW_ANOVA (line 82)
[out_datasets(1),out_datasets(2),message_string,cluster_distribution]=RLW_ANOVA(datasets,configuration.parameters.factor_data,configuration.parameters.table_data,'enable_parallel',configuration.parameters.enable_parallel,'alpha',configuration.parameters.alpha,'permutation',configuration.parameters.permutation,'num_permutations',configuration.parameters.num_permutations,'cluster_statistic',configuration.parameters.cluster_statistic,'cluster_threshold',configuration.parameters.cluster_threshold);

Error in letswave_gui>menu_callback (line 387)
[configuration,datasets]=eval(eval_st);

Error while evaluating Menu Callback
