### ISSUE TITLE
Error running ICA - datasets do not have matching unmixing matrices

### ISSUE THREAD

**Issue by GiuliaL** [NOCIONS/letswave6#13]
Hi Andre,
When applying the ICA filter right after computing the ICA matrix (merged datasets option), I get the following error:

ERROR : the datasets do not have matching unmixing matrices

It is strange, because this happens only with the data from my last subject (I think the only one pre-processed 100% with Letswave6). With all my other data, the ICA filter works perfectly, and I don't think I am doing anything different. Do you have any idea what the problem could be?

Thanks in advance!

Giulia

**Comment by amouraux** [comment]
Can you check whether the problem persists? I cannot reproduce the problem on my setup, even when using your files. Note that there was a bug in the update function. I just updated manually the LW6 files on your computer.

**Comment by GiuliaL** [comment]
I still got the problem when applying the filter, so I re-ran the whole ICA from scratch and it finally worked.
Thanks!
