### ISSUE TITLE
Letswave 6. Grand Average (weighted)

### ISSUE THREAD

**Issue by sabaristei** [NOCIONS/letswave6#130]
Dear André, 
I used Grand Average on SNR data (subtraction). It is usually a smooth operation. However, this time the function reports an error:
>Array dimensions must match for binary array op.
>Error in RLW_grand_average (line 60)
>    out_data=out_data+(data*dataset_weights(setpos));

>Error in LW_grand_average (line 76)
>[out_datasets(1).header,out_datasets(1).data,message_string]=RLW_grand_average(datasets,'dataset_weigh>ts',configuration.parameters.dataset_weights);
        
>Error in letswave_gui>menu_callback (line 387)
>Error while evaluating Menu Callback.

Arrays have all 6 dimensions, the only dimension with different values is the X-dimension. I used the values of X for each dataset to set the weights, but nothing changed. Could you suggest a way to solve the issue?
Thank you in advance.

Best,
Sabrina

**Comment by amouraux** [comment]
If you get this error, it means that the different datasets do not have the same number of data points per epoch, or the same number of channels, index, etc…
Can you double check?

Best wishes,
André

--
André Mouraux
Institute of Neuroscience (IONS)
Faculty of Medicine
University of Louvain
53, Avenue Mounier (B1.53.04)
B1200, Brussels, Belgium

Web: http://www.nocions.org
Tel : +32.2.764.5447



On 29 May 2017, at 15:21, sabaristei <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear André,
I used Grand Average on SNR data (subtraction). It is usually a smooth operation. However, this time the function reports an error:

Array dimensions must match for binary array op.
Error in RLW_grand_average (line 60)
out_data=out_data+(data*dataset_weights(setpos));

Error in LW_grand_average (line 76)
[out_datasets(1).header,out_datasets(1).data,message_string]=RLW_grand_average(datasets,'dataset_weigh>ts',configuration.parameters.dataset_weights);

Error in letswave_gui>menu_callback (line 387)
Error while evaluating Menu Callback.

Arrays have all 6 dimensions, the only dimension with different values is the X-dimension. I used the values of X for each dataset to set the weights, but nothing changed. Could you suggest a way to solve the issue?
Thank you in advance.

Best,
Sabrina

**Comment by sabaristei** [comment]
...checked again: indices, channels, epochs are identical, as they are Y and Z size, but different data points (both XStep and X Srate vary across datasets). Is there a way around it?
Thank you for helping out.

Sabrina

**Comment by amouraux** [comment]
Could you resample them (using the resample function) so that they have matching xsize and xstep?

André



On 29 May 2017, at 15:50, sabaristei <notifications@github.com<mailto:notifications@github.com>> wrote:


...checked again: indices, channels, epochs are identical, as they are Y and Z size, but different data points (both XStep and X Srate vary across datasets). Is there a way around it?
Thank you for helping out.

Sabrina

**Comment by sabaristei** [comment]
...many thanks. It works!

Best wishes,
Sabrina
