### ISSUE TITLE
Issue Importing .set file from EEGLAB

### ISSUE THREAD

**Issue by tjames22** [NOCIONS/letswave6#132]
Hello, 
I get the following error message when trying to import a file from EEGLAB: 

Undefined function or variable 'ft_struct2double'.

Error in ft_datatype_sens (line 164)
    sens = ft_struct2double(sens);

Error in ft_read_header (line 2391)
  hdr.elec = ft_datatype_sens(hdr.elec);

Error in ft_read_data (line 200)
  hdr = ft_read_header(filename, 'headerformat', headerformat, 'chanindx', chanindx,
  'checkmaxfilter', checkmaxfilter);

Error in RLW_import_SET (line 26)
dat=ft_read_data(filename);

Error in LW_import_SET (line 86)
            [out_datasets(filepos).header out_datasets(filepos).data
            message_string]=RLW_import_SET(filename);

Error in letswave_gui>menu_callback (line 387)
                [configuration,datasets]=eval(eval_st);
 
Error while evaluating Menu Callback

Please advise

**Comment by amouraux** [comment]
Sorry for this, the function was missing from the ‘external’ functions.
Problem should be solved after updating.

Kind regards,
André Mouraux

On 20 Jun 2017, at 20:53, tjames22 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I get the following error message when trying to import a file from EEGLAB:

Undefined function or variable 'ft_struct2double'.

Error in ft_datatype_sens (line 164)
sens = ft_struct2double(sens);

Error in ft_read_header (line 2391)
hdr.elec = ft_datatype_sens(hdr.elec);

Error in ft_read_data (line 200)
hdr = ft_read_header(filename, 'headerformat', headerformat, 'chanindx', chanindx,
'checkmaxfilter', checkmaxfilter);

Error in RLW_import_SET (line 26)
dat=ft_read_data(filename);

Error in LW_import_SET (line 86)
[out_datasets(filepos).header out_datasets(filepos).data
message_string]=RLW_import_SET(filename);

Error in letswave_gui>menu_callback (line 387)
[configuration,datasets]=eval(eval_st);

Error while evaluating Menu Callback

Please advise
