### ISSUE TITLE
Problems extracting data in excel

### ISSUE THREAD

**Issue by LiesaZw** [NOCIONS/letswave6#133]
Hey,
when i want to extract any kind of data in excel, it appears this error message:

Undefined function 'actxserver' for input arguments of type 'char'.

Error in GLW_ExtractIntervals>process_button_Callback (line 289)
    Excel = actxserver('Excel.Application');

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in GLW_ExtractIntervals (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)GLW_ExtractIntervals('process_button_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating uicontrol Callback

I tried to update the plugin, but it didn't help.
Do you have any other idea? Thanks for your help.

Greetings

Liesa

**Comment by amouraux** [comment]
Are you trying this on a Mac?
