### ISSUE TITLE
cluster-based permutation ANOVA, results

### ISSUE THREAD

**Issue by PietroSarasso** [NOCIONS/letswave6#135]
Dear experts,
I run a point-by-point ANOVA on my ERP data (1 factor, 5 levels). I not very sure of how to read and interpret the results. The outcome of the analysis are two files, one for the p-value and one for the F-value. These files have 4 epochs as you can see here:
![p-value](https://user-images.githubusercontent.com/32293070/30850499-ff35ce20-a2a5-11e7-90e8-23dc498794fd.png)
The first epoch is clearly the uncorrected p-value, but what about the last three? How do I identify significant clusters?
hope you can help me.
Bests
Pietro

**Comment by EVale** [comment]
Dear Pietro,

the second epoch is the one you want to look at as to identify the thresholded p or t or F value.
Epoch 3 should give you the actual significance of each cluster using the distribution of all the clusters following permutation.
Epoch 4 should give you the same type of information but using the max clustersize values.

I'm not sure if the wiki provides this information and I hope this is correct.
Perhaps others here may want to clarify.

Best wishes,

e
