### ISSUE TITLE
Importing .set to Letswave 6

### ISSUE THREAD

**Issue by Razieh-Alemi** [NOCIONS/letswave6#140]
Hello,
I am trying to import  an EEGLAB set file to Letswave 6. When I go to File -> Import Signals -> EEGLAB set file, there is no option to select file. I updated my Letswave, but no change.
Would you please help me to find how I can import it.
Best,

Razieh

**Comment by amouraux** [comment]
Strange.
It works on my setup.
Can you send me a screenshot of the GUI?
I know that there are a few issues with Windows 10 not always displaying the graphical interfaces correctly.

André


On 2 Feb 2018, at 19:20, Razieh-Alemi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I am trying to import an EEGLAB set file to Letswave 6. When I go to File -> Import Signals -> EEGLAB set file, there is no option to select file. I updated my Letswave, but no change.
Would you please help me to find how I can import it.
Best,

Razieh

**Comment by Razieh-Alemi** [comment]
Hello  André,
Thanks for your response. You are right, I am working on windows 10. I changed GPU setting and now it works.

Best,
Razieh
