### ISSUE TITLE
GLW_import_EGI issues

### ISSUE THREAD

**Issue by Thoxic** [NOCIONS/letswave6#141]
The importing EGI function actually accepts and correctly imports .bin files (as far as I know found within .mff folders).
Although the function implies to be able to handle .mff folders (which the import function from fieldtrip indeed can do), it is impossible to select the .mff folder, due to the uigetfile() function. I have no idea whether there would be an easy fix GUI-wise.
A possible fix outside of the GUI would be to not use the GUI, but use straight up code (this would circumvent the uigetfile() function.) I don't have enough experience in matlab to recognize whether this is possible for letswave6 or not.
Cheers!

**Comment by amouraux** [comment]
I have modified the GUI. Added an additional button to select a folder using uigetdir. Hope it works!
