### ISSUE TITLE
ANOVA changing in speed usign different computers 

### ISSUE THREAD

**Issue by mdiano** [NOCIONS/letswave6#142]
Dear letswave experts,
we are encountering an issue during ANOVA analysis (with the option clusterize-based permutation testing) using different computers. When we use the PC one, the analysis finishes in about 4 hours. When we use the MAC one, the same analysis finishes in about 4 days. Do you know what it could be the problem? Did we miss some plugins in matlab or in letswave? Sorry if I neglected any important information, let me know and I will integrate it. Below are the specifications of our computers.
Thank you in advance 
Best
Matteo

PC: windows 10
16 GB ram 
intel i7-4790 3.6 GHz
nvidia geforce gtx 950
Matlab R2015a

MAC:  OSx Yosemite
64 GB ram
Intel Xeon E5 3.5 GHz
AMD FirePro D500
Matlab R2014b

**Comment by amouraux** [comment]
I have not noticed such a performance issue on my own Mac. Could be related to the fact that you are using a relatively old version of Matlab. I strongly suggest that you update Matlab on both of your setups.
