### ISSUE TITLE
issues in importing .mff files (EGI system)

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#153]
Multiple users are encountering issues when trying to import .mff files (folders) exported from the EGI systems. 

Error while evaluating uimenu Callback

Undefined function 'ft_notification' for input arguments of type 'char'.

Error in ft_error (line 39)
  ft_notification(varargin{:});

Error in ft_read_header (line 202)
    ft_error('file or directory ''%s'' does not exist', filename);

Error in RLW_import_EGI (line 54)
        hdr=ft_read_header(filename);

Error in LW_import_EGI (line 88)
            [out_datasets(filepos).header out_datasets(filepos).data
            message_string]=RLW_import_EGI(filename,'concatenate',configuration.parameters.concatenate,'implementation',configuration.paramete
            Error in letswave_gui>menu_callback (line 387)
                [configuration,datasets]=eval(eval_st);
 
Error while evaluating uimenu Callback

**Comment by hughherald** [comment]
Dear Diana,

Importing EGI files is really troublesome. Maybe the current solution would be transform the dataset to '.raw' format. 

We have get some technique support from EGI engineers. We are trying to fix this bug.

Best,
Gan
