### ISSUE TITLE
Marker to marker segmentation

### ISSUE THREAD

**Issue by fnedez** [NOCIONS/letswave6#166]
Hello,
in a EEG experiment, I presented a fixation cross followed by a video followed by an image.
Videos have different time durations. I putted a trigger on the video onset and another on the
image onset.

For example:
30 = trigger onset video
31 = trigger onset image

My question is: Is it possible to do a segmention based on the triggers?
Like, Segmentation (from 30 to 31)?
Thanks in advance,
fnedez

**Comment by hughherald** [comment]
Sorry, as I know Letswave only support the segmentation with fix length data.
