### ISSUE TITLE
Lets6 stuck when importing Lets5 files

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#2]
30/03/2015
I first updated Lets6 and then attempted to import averaged merged single subjects files (4 files 18 subjects each) into lets6 but it stucks at the first file.
Let me know if I need to send any file.

Best,

elia

**Comment by amouraux** [comment]
Can you copy-paste the error message?

Best wishes,
André

--
André Mouraux
Institute of Neuroscience (IONS)
Faculty of Medicine
University of Louvain
53, Avenue Mounier (B1.53.04)
B1200, Brussels, Belgium

Web: http://www.nocions.org
Tel : +32.2.764.5447

**Comment by EVale** [comment]
Dear André,

I tried now on a different computer and it worked. However, when I open the
files I see"empty" files

[image: Inline images 1]

In addition, when I click on the topright x to close them they do not close.

PLease note that yesterday I attempted to import having two instances of
matlab opened (ith Lets5 and 1 with Lets6).
This may have had a significant effect...
