### ISSUE TITLE
Analyse data from accelerometer

### ISSUE THREAD

**Issue by gualoe** [NOCIONS/letswave6#35]
Hello,
we would like to use letswave to preprocess accelerometer data, using just one channel. I've tried to upload a simple ascii file (no header information) specifying sampling rate etc., but it doesn't work,

Best wishes,
Guido

**Comment by amouraux** [comment]
Dear Guido,

Normally, it should work. 
Can you give me a sample ASCII file so that I can test it?

Of note, I remember that I fixed a bug regarding the ASCII import a few weeks ago. Can you make sure that you have the latest updated version?

Best wishes,
André

**Comment by gualoe** [comment]
Dear Andre,

apologies for the delay, I have been annual leave, please find attached the relevant file in .csv and ascii format, the sampling rate is 0.5 Hz. The file does not actually contain raw acceleration data, but reflects cross recurrence of acceleration. Best, Guido




 
………………………………………...
Dr Guido Orgs
Lecturer in Psychology
Department of Life Sciences
College of Health and Life Sciences
Brunel University London

Email: guido.orgs@brunel.ac.uk <mailto:guido.orgs@brunel.ac.uk>
Phone: +44(0)18952 67707
 www.brunel.ac.uk


> On 21 Aug 2015, at 06:44, André Mouraux <notifications@github.com> wrote:
> 
> Dear Guido,
> 
> Normally, it should work. 
> Can you give me a sample ASCII file so that I can test it?
> 
> Of note, I remember that I fixed a bug regarding the ASCII import a few weeks ago. Can you make sure that you have the latest updated version?
> 
> Best wishes,
> André
> 
> > On 12 Aug 2015, at 16:02, gualoe <notifications@github.com> wrote:
> > 
> > Hello,
> > we would like to use letswave to preprocess accelerometer data, using just one channel. I've tried to upload a simple ascii file (no header information) specifying sampling rate etc., but it doesn't work,
> > 
> > Best wishes,
> > Guido
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/NOCIONS/letswave6/issues/35>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/NOCIONS/letswave6/issues/35#issuecomment-133295468>.
> 


62.90046296
60.70245726
60.40277778
60.42592593
60.36841168
60.2647792
60.88657407
60.51834046
60.41452991
59.45868946
36.09455128
66.59757835
61.86538462
61.54291311
61.64618946
61.24341168
61.58903134
61.40473647
60.99038462
61.40473647
61.23201567
61.30110399
61.38158832
61.50854701
61.71599003
61.53116097
61.93429487
61.85363248
61.55430912
61.40491453
61.46225071
61.19729345
61.23219373
61.23201567
61.3468661
61.61182336
61.72702991
61.69230769
61.51976496
61.40509259
61.94604701
61.95762108
61.66951567
61.91150285
61.75035613
61.7962963
61.38158832
61.54273504
61.43945869
61.49626068
61.58885328
60.86396011
60.55252849
60.63319088
60.69070513
60.50658832
60.59864672
60.49519231
60.23023504
60.28792735
60.24180912
60.46047009
61.08208689
63.08547009
62.48717949
61.12820513
61.62339744
61.00160256
62.00338319
62.14155983
62.1994302
62.37197293
62.44106125
57.42111823
57.45566239
61.8539886
62.39458689
63.32763533
65.45779915
63.64992877
62.33707265
62.38319088
62.40651709
62.16542023
62.71777066
63.14280627
63.00534188
62.77492877
62.51014957
62.47560541
62.49839744
60.89797009
60.73682336
60.4837963
60.55270655
61.89975071
60.43767806
60.39138177
61.68126781
62.85559117
62.11841168
61.16257123
62.03846154
61.41666667
62.22240028
61.31267806
60.94408832
60.51834046
63.9613604
61.08262108
62.59009972
62.53329772
62.9136396
62.47560541
62.52154558
62.55591168
62.79807692
62.74038462
62.27973647
62.69391026
62.37161681
62.37161681
62.4298433
62.14173789
62.26780627
62.64832621
62.26780627
62.10737179
61.77332621
62.44141738
62.15349003
61.2900641
59.8497151
57.58244302
56.34935897
56.81018519
57.25979345
56.93678775
56.46492165
56.55698006
57.21349715
56.61413818
56.14173789
54.46153846
52.80306268
54.94551282
50.54700855
50.6741453
51.13479345
53.34472934
51.79113248
49.82229345
51.53703704
51.190349
53.75819088
46.76887464
47.96830484
45.76798433
46.13621795
42.31445869
43.05146011
40.37945157
37.33992165
39.12589031
36.07460826
40.67966524
38.65277778
37.28276353
39.92004986
37.67343305
40.90954416
38.68732194
33.06784188
35.97008547
33.31000712
35.07175926
34.78454416
32.33155271
38.30751425
37.63924501
38.01958689
35.04985755
39.29807692
46.35541311
38.66292735
43.52279202
44.91684473
38.19195157
36.30591168
36.38479345
35.59081197
39.14779202
34.58867521
37.0281339
44.44462251
42.54700855
40.56428063
37.6980057
36.04967949
39.38034188
34.65758547
37.02920228
38.3974359
39.76851852
41.89832621
40.35754986
34.81962251
34.26638177
40.69195157
35.6116453
37.85968661
35.30021368
42.72881054
46.26210826
41.98023504
36.75462963
39.66435185
36.5582265
33.87446581
33.05502137
28.15438034
30.50035613
27.87517806
23.68269231
30.37286325
26.47026353
25.44622507
27.47275641
23.16702279
23.31641738
25.92022792
22.71759259
25.08903134
26.98985043
30.01727208
31.7781339
30.39672365
28.63514957
27.93287037
29.70673077
26.74661681
29.36057692
28.19622507
30.40527066
28.01282051
28.38372507
25.49198718
23.28133903
24.75569801
23.1545584
27.06018519
24.98308405
21.57710114
22.68393875
22.13942308
23.50017806
26.48272792
31.93928063
27.62268519
30.13087607
26.50516382
26.60933048
24.73326211
26.91826923
28.12767094
30.56054131
29.77564103
29.8215812
31.68571937
31.17913105
31.36556268
34.81908832
37.03970798
40.24358974
37.23575499
37.00641026
37.87962963
47.18571937
37.79932336
39.36609687
40.10327635
38.6994302
39.02207977
42.38425926
45.50391738
38.2619302
41.39173789
41.31196581
35.01353276
35.63461538
39.69978632
37.55947293
36.78650285
33.3912037
37.6980057
46.26282051
45.91720085
39.38016382
37.57140313
36.37393162
34.31267806
30.71883903
27.51834046
30.97346866
26.60790598
28.58867521
22.49910969
23.16435185
23.08600427
23.10915242
25.65331197
27.21901709
24.24946581
22.95779915
20.78222934
18.78080484
19.73361823
16.03899573
19.88586182
20.47168803
19.47061966
17.32905983
18.45601852
17.3855057
22.70744302
16.72792023
23.09633191
20.5639245
21.39245014
22.14155983
27.08297721
25.37802707
27.38176638
22.99323362
24.30608974
25.42183048
26.80288462
30.06285613
28.62482194
20.71456553
25.42343305
21.6355057
22.4880698
23.47792023
24.09740028
24.59419516
25.13354701
24.96349715
21.19871795
19.91933761
21.28952991
21.3707265
22.79825499
24.34241453
23.92788462
22.93839031
26.09152422
26.73504274
27.59811254
26.59775641
24.07567664
19.70049858
20.89779202
19.46937322
21.86574074
19.65384615
20.6011396
18.68589744
18.51673789
16.76655983
17.65010684
16.17432336
18.56196581
15.16417379
15.96990741
15.4269943
14.16470798
15.10505698
17.54825499
17.80039174
18.05270655
20.43536325
23.31410256
22.55448718
22.87037037
22.16310541
24.05448718
24.12126068
23.43180199
25.40010684
28.84312678
28.15188746
33.81463675
31.47952279
33.27564103
33.17289886
36.48771368
34.80591168
30.21456553
37.74269943
35.63621795
38.19230769
37.51353276
33.48183761
34.36876781
30.34009972
29.11841168
30.51353276
31.74412393
36.25890313
35.75053419
35.24501425
29.56873219
33.09099003
31.7900641
30.30448718
35.04896724
31.79042023
31.33992165
32.44533476
31.2156339
33.54131054
32.49341168
32.14814815
30.42022792
33.78044872
31.87179487
31.79113248
33.0210114
33.81606125
32.14654558
32.6769943
32.98985043
29.27938034
28.65972222
34.03258547
48.94551282
48.61289174
49.01549145
52.10381054
51.36663105
53.18162393
53.67663818
56.2113604
56.24554843
56.56926638
57.8707265
53.22952279
56.30430912
58.03009259
56.5920584
55.11680912
51.39725783
55.86289174
57.40900997
55.81891026
56.33956553
56.47453704
53.4789886
52.7576567
54.88728632
53.61948006
56.85416667
52.5162037
59.15918803
54.06766382
57.03935185
56.26923077
55.07460826
57.85897436
48.3019943
36.62553419
35.15153134
31.31855413
28.59864672
27.48450855
30.49964387
30.81178775
29.25587607
33.09116809
30.28027066
28.94693732
26.2857906
27.88782051
29.45316952
28.63603989
27.20708689
26.14939459
30.08475783
28.95868946
28.47204416
30.30270655
30.20868946
31.37517806
29.24483618
30.15616097
26.68963675
30.06499288
26.5997151
23.3616453
27.40295584
30.87126068
28.62660256
29.51940883
28.27831197
27.63586182
33.48308405
33.57674501
40.4122151
44.87054843
52.28596866
52.02012108
54.02225783
54.42646011
52.15954416
50.87998575
52.25178063
49.98076923
47.5892094
48.1412037
51.05252849
52.93073362
53.29950142
45.29718661
55.35737179
60.7247151
53.47061966
50.99661681
50.89209402
55.2914886
47.7037037
51.16951567
48.63603989
49.31641738
45.98789174
45.74483618
46.2423433
50.81232194
48.78311966
45.2605057
46.46919516
49.46545584
51.61609687
47.17254274
54.00231481
57.20067664
60.18429487
62.24448006
59.94391026
58.68803419
59.26139601
58.29789886
59.6917735
58.04220085
50.60345442
52.93002137
47.86093305
38.90580484
19.54807692
19.59740028
17.44355413
18.51424501
17.36253561
19.71260684
26.90633903
34.71474359
44.84740028
51.1798433
55.17450142
57.52421652
61.5329416
51.2261396
48.98148148
46.56232194
50.47809829
53.50623219
51.9417735
52.37695869
47.31125356
50.47667379
44.47881054
43.39725783
46.08938746
41.28935185
33.7170584
40.29932336
41.36111111
37.48112536
39.64440883
31.71153846
34.74982194
38.19159544
40.47115385
35.33742877
32.76851852
31.7781339
30.14227208
30.57959402
29.25658832
27.95495014
33.19266382
37.6741453
50.02938034
48.85505698
50.13034188
50.0534188
54.77279202
59.11413818
51.43073362
50.48860399
55.95726496
34.51816239
31.26210826
39.13497151
52.73557692
38.2843661
39.87375356
43.43073362
50.47738604
46.74875356
36.71794872
38.64262821
49.12304131
41.41684473
22.91328348
35.77190171
51.94106125
28.87838319
26.95495014
41.70512821
34.33600427
40.6102208
44.28329772
53.41292735
47.18233618
24.70103276
37.59561966
39.37873932
48.78561254
35.71438746
30.38514957
49.82175926
41.39512108
16.57959402
36.78846154
46.14707977
17.81303419
33.35737179
50.63764245
50.71777066
20.96474359
57.71047009
61.31285613
61.49697293
61.19764957
60.97863248
61.16274929
60.86324786
60.65598291
61.07086895
61.03614672
61.23219373
61.7156339
61.69266382
61.09383903
60.79451567
60.88675214
61.19747151
61.53133903
44.28454416
48.21082621
62.01442308
61.34704416
61.33529202
61.92254274
61.86538462
43.81143162
51.39975071
64.01905271
58.37624644
56.16577635
59.07905983
60.94391026
56.17788462
41.87571225
61.45067664
61.49661681
61.46207265
60.90954416
60.11467236
28.5548433
50.07389601
57.50089031
64.58244302
67.64369658
66.67770655
66.97774217
62.83226496
59.95388177
23.32674501
28.82051282
34.63425926
32.00676638
36.07336182
49.84561966
49.02759972
51.36485043
57.11075499
56.91292735
53.26406695
60.69088319
61.81944444
60.38051994
61.12856125
62.57923789
63.88051994
65.18126781
61.78454416
46.29825499
32.11093305
40.78543447
40.44764957
41.66987179
40.23023504
43.61556268
54.62375356
60.80591168
60.69017094
61.72738604
64.01816239
64.61663105
60.33404558
62.49893162
61.02492877
29.00231481
34.96777066
40.65633903
39.71171652
39.17111823
37.65117521
42.53240741
48.87660256
60.24180912
63.21225071
61.877849
61.50819088
61.53240741
61.30110399
60.50641026
60.7022792
61.45121083
61.18589744
61.35844017
52.33279915
37.82264957
49.97168803
50.78828348
51.83707265
51.79059829
56.98450855
63.76638177
59.66595442
64.73183761
62.68251425
62.87856125
63.01691595
62.29113248
62.56766382
63.98397436
62.70601852
62.65954416
62.71741453
62.77475071
60.81695157
59.04433761
50.35042735
60.41417379
60.70245726
32.40224359
28.2218661
26.21848291
34.58849715
32.73344017
43.47827635
46.8511396
53.57478632
60.51816239
59.12482194
62.46403134
61.70405983
64.2022792
63.6144943
62.39440883
60.73717949
45.66417379
36.2590812
37.1102208
38.65259972
38.23789174
41.71545584
35.99287749
39.2394943
49.11841168
53.27546296
57.3406339
54.95673077
56.2576567
57.63924501
61.8883547
59.40117521
62.12962963
61.91096866
61.75017806
62.64850427
61.99198718
65.52742165
62.34900285
34.3082265
54.67022792
59.07852564
58.99786325
57.57033476
57.89227208
59.8616453
58.7099359
60.16132479
60.94337607
59.3897792
60.61075499
61.00178063
62.7289886
61.55448718
61.19729345
61.49661681
48.69462251
35.9360755
38.45637464
39.25178063
39.74750712
42.78685897
44.37571225
47.55377493
54.25498575
60.95584046
61.2781339
59.81623932
61.11716524
56.69480057
41.41542023
55.41791311
54.03525641
55.61342593
55.32460826
56.89155983
56.98361823
55.9585114
57.62713675
61.45049858
61.13995726
61.70441595
60.690349
62.17610399
51.01940883
46.60861823
53.20655271
51.53685897
51.01923077
49.53311966
48.42877493
47.0343661
50.69675926
55.22222222
52.70049858
60.33422365
56.3497151
59.68821225
59.57318376
63.90277778
64.2829416
57.33974359
23.1545584
30.4775641
51.4909188
60.18429487
59.8616453
60.66773504
59.99946581
60.42539174
59.87286325
60.75890313
61.22061966
65.00943732
62.48771368
61.69266382
61.10559117
39.81570513
43.92752849
43.35060541
49.64850427
59.23967236
57.20121083
60.72507123
55.43999288
60.92147436
54.68037749
59.51655983
53.83974359
57.88158832
56.59081197
62.36039886
56.13087607
63.78881766
62.39494302
64.98611111
60.39155983
57.13194444
63.04950142
62.30163818
67.21866097
62.2099359
56.41898148
60.31054131
62.49804131
42.02581909
56.8335114
62.02706553
60.63372507
60.94444444
61.34704416
59.71189459
29.56695157
27.08173077
24.99626068
27.63443732
30.15509259
27.95726496
24.29558405
29.14262821
28.64690171
40.47133191
55.47542735
60.14975071
60.52938034
59.25160256
44.38675214
59.62037037
60.11538462
60.50641026
59.06695157
54.10523504
53.74821937
60.04594017
61.63497151
56.23504274
46.03258547
50.59277066
49.6607906
50.62767094
49.31481481
51.14547721
54.28881766
58.27332621
59.45904558
59.90758547
52.42325499
60.41488604
57.73130342
62.30324074
60.51798433
59.5849359
55.08279915
56.28133903
56.8792735
55.77350427
52.21581197
57.38639601
53.34508547
59.3897792
59.91933761
59.42361111
59.63141026
59.24020655
59.91933761
59.28614672
59.6664886
60.16114672
59.64245014
60.94426638
59.40099715
60.1264245
61.46260684
60.88621795
61.15153134
60.05769231
60.72542735
61.04807692
60.58707265
60.44889601
60.84027778
59.93108974
58.83725071
60.74893162
60.88621795
60.86360399
58.79095442
62.15295584
61.94604701
53.49358974
56.52225783
51.26086182
49.59152422
60.95530627
61.6235755
60.57549858
58.42289886
59.28632479
61.49697293
61.23254986

**Comment by amouraux** [comment]
Dear Guido,

I made some additional fixes to the import ASCII functions. 
It should now work fine?

Best wishes,
André

**Comment by gualoe** [comment]
Dear Andre,

thanks for looking into this. I’m currently switching institutions and as yet without matlab access but will check soon,

Best,
Guido


-----------------------------------------------
Dr Guido Orgs
Lecturer, Department of Psychology
Goldsmiths, University of London

Whitehead Building, Room W200/6
New Cross, London, SE14 6NW

E-mail: g.orgs@gold.ac.uk<mailto:g.orgs@gold.ac.uk>
Phone: +44 (0)20 7896 2719







On 20 Oct 2015, at 10:57, André Mouraux <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Guido,

I made some additional fixes to the import ASCII functions.
It should now work fine?

Best wishes,
André
