### ISSUE TITLE
bug in chunk epochs

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#36]
Subscript indices must either be real positive integers or logicals.

Error in RLW_segmentation_chunk (line 110)
        out_data(k,:,:,:,:,:)=data(epoch_pos,:,:,:,:,chunks_dxstart(chunk_pos):chunks_dxstart(chunk_pos)+(chunk_size_dx-1));
        
Error in LW_segmentation_chunk (line 82)
            [out_datasets(setpos).header,out_datasets(setpos).data,message_string]=RLW_segmentation_chunk(datasets(setpos).header,datasets(setpos).data,'chunk_onset',configuration.parameters.chunk_on
            Error in letswave_gui>menu_callback (line 226)
                        [configuration,datasets]=eval(eval_st);
 
Error while evaluating uimenu Callback

>>

**Comment by amouraux** [comment]
This error occurs when the defined chunks are outside the limits of the chunked epoch. 
I have modified the function so that this is tested now before attempting to chunk the epochs.
