### ISSUE TITLE
EPS conversion of 3D headmaps

### ISSUE THREAD

**Issue by flamancini** [NOCIONS/letswave6#37]
Hello,

Thanks very much for having released Letswave 6, we now use it routinely with ease.

I have encountered a problem in exporting figures of 3D headmaps in vectorial format (EPS).

The files are exported without errors but they cannot be read/converted by PostScript.  The same procedure on scalpmaps and waveforms does not cause any problem, and PostScript conversion works fine.

I am using Matlab_R2014b on a MAC OS X 10.10.5. I am unable to open the exported EPS files (containing headmaps) in Preview, Adobe Illustrator and Photoshop.

For your reference, here is one of the problematic files as example: https://dl.dropboxusercontent.com/u/104190139/avg_scalp_n2_rh.eps

Many thanks for the support.

Best wishes

Flavia Mancini
UCL/NPP UK

**Comment by amouraux** [comment]
Dear Flavia,

We almost finished writing a new head plot function...
