### ISSUE TITLE
delete duplicate events

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#38]
There is a possible bug in the function 'delete duplicate events'--> delete duplicate events having latency differences smaller than 

Error while evaluating uimenu Callback

Undefined variable "configuration" or class "configuration.parameters.tolerance".

Error in RLW_events_delete_duplicate (line 59)
    message_string{1}=['Tolerance : ' num2str(configuration.parameters.tolerance)];

Error in LW_events_delete_duplicate (line 79)
            [out_datasets(setpos).header,message_string]=RLW_events_delete_duplicate(datasets(setpos).header,'exact_latencies',configuration.parameters.exact_latencies,'tolerance',configuration.param
            Error in letswave_gui>menu_callback (line 251)
                        [configuration,datasets]=eval(eval_st);
 
Error while evaluating uimenu Callback

**Comment by amouraux** [comment]
Bug is fixed!
André
