### ISSUE TITLE
GUI table

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#43]
after selecting the ROI and selecting 'table' this mistake is shown, even after updating to the last version 
Index exceeds matrix dimensions.

Error in CGLW_multi_viewer>table_btn_Callback (line 1344)
            [ymax,dx]=max(squeeze(output.tpdata_y(datasetpos,epochpos,chanpos,dx1:dx2)));

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in CGLW_multi_viewer (line 24)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)CGLW_multi_viewer('table_btn_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uicontrol Callback

**Comment by amouraux** [comment]
Should be fixed now!
