### ISSUE TITLE
Change multiviewer plot options with override

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#44]
Hi,

I tried to customise the plotting options for the multiviewer by modifying line 543 in GCLW_multi_viewer.m (change stem marker from default to '.')

userdata.plot_handle(row_pos,col_pos,wave_pos).handle=stem(userdata.axes_handle(row_pos,col_pos),squeeze(output.tpdata_x(row_pos,col_pos,wave_pos,:)),squeeze(output.tpdata_y(row_pos,col_pos,wave_pos,:)),'Color',linecolors(wave_pos,:),'Marker', '.');

I copied the file in the "override" folder (with and without adding an extra CGLW folder) and by saving directly within the "core functions" folder, but none of these appear to be working. The multiviewer still displays the default 'o' marker for stems. 

Is there something I missed? 

Thanks in advance for your help!

**Comment by amouraux** [comment]
After updating, you should be able to ‘override’ by putting it in the override folder (not in a subfolder). 

The reason why it still displays the default ‘o’ marker is that you need to change two lines (lines 690 and 544; i.e. the create_graph and update_graph_data functions).

Note that I just made your change in the main function, as this improves the stem plots…

Best wishes,
André
