### ISSUE TITLE
Display GUI in Waveforms figure ceator and in Fast CWT (Mourau et al.)

### ISSUE THREAD

**Issue by cedlenoir** [NOCIONS/letswave6#45]
The upper part of the windows of the GUI of these 2 functions are not visible. It seems similar to the previous issue that I reported last week.

**Comment by amouraux** [comment]
Fixed the display problem in the Fast CWT. 

However, I could not find any issue with the Waveforms figure creator?

André

**Comment by cedlenoir** [comment]
I just update it , it is fine now. thanks
Cédric.
