### ISSUE TITLE
LW5 plugins for LW6

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#47]
The modified plugins from LW5 do not appear with the latest update of LW6?

**Comment by amouraux** [comment]
No, because Bruno did not want them to be included in LW6.
You can download them from the LW6 github wiki for now.
Then, we will see whether we can host them somewhere with some protection…

Best wishes,
André

**Comment by JoanLS** [comment]
Thanks André! 

Apologies for spamming but I have found a couple more plugins from LW5 that would need to be converted. 

https://dl.dropboxusercontent.com/u/20128470/To%20Add.zip

I am not 100% sure of the authors, but I think it's as follows

- GLW_interpolate_channels_of1epoch by Dan Nemdorov
- GLW_manage_electrodes by Gilles Vertongen
- GLW_normalize_topographies by Corentin Jacques
- GLW_segment_recording_blocks by Dan Nemdorov
- GLW_sumepochs by Dan Nemdorov
- GLW_XYZnorm by Corentin Jacques
- LW_PreprocessDataNancy by Goedele Van Belle

Also, there are a couple of plugins currently listed that were not created by Corentin but by Goedele
- GLW_conditionAverage
- GLW_peakPreview

As always, thank you very much in advance for your help!

Best,
Joan

**Comment by amouraux** [comment]
Ok. Will try to add them ASAP!
André

**Comment by amouraux** [comment]
For the plugin GLW_interpolate_channels_of1epoch, I am missing the file LW_interpolate_channels_of1epoch.m

**Comment by JoanLS** [comment]
Dear André,

It seems that this plugin is not fully developed (Dan created it I think)
and nobody in the lab has the .m file. We can leave out this plugin for LW6.

Thank you very much,
Joan

**Comment by amouraux** [comment]
Dear Joan, 

I added some additional plugins. 

There are still a couple of plugins that I cannot convert because of missing functions : 

GLW_normalize_topographies
- Missing LW_norm_topos

GLW_manage_electrodes
- Missing LW_switch_electrodes

GLW_sumepochs
- Missing LW_sumepochs

LW_preprocess_data_Nancy
- Explanations required as to what this function does

**Comment by JoanLS** [comment]
Dear André,

Please find the missing functions in attachment.

As for* LW_preprocess_data_Nancy*, this is a plugin for preliminary
analysis of intracerebral data. It mainly integrates pre-existing functions
from Letswave in a GUI.
-  imports data in both .TRC format (Micromed recording format) and
Brainvision .edf format

- search for events (digital triggers), in absence of events, select an EEG
channel to use as analog trigger via "create events from level trigger" (in
our case, we have the channel *MKR1+* recording the photodiode)

- visualise recording segments with triggers and select relevant blocs
(with possibility to manually move start & end of blocs)

- import stimulation information from Sinstim output (select Sinstim .mat
outputs, then select .txt file with trial conditions)

- crop and run FFT on selected EEG segments

I have included a .zip file with an example TRC file and the Sinstim
output, so you can see what it looks like :*
https://dl.dropboxusercontent.com/u/20128470/LW_PreprocessNancy_Example.zip
<https://dl.dropboxusercontent.com/u/20128470/LW_PreprocessNancy_Example.zip>*.
In this experiment, images are shown at 6 Hz, with alternating scrambled &
face images (so frequency of interest = 3 Hz).

Have a nice day,
Joan


On 12 December 2015 at 07:57, André Mouraux <notifications@github.com>
wrote:

> Dear Joan,
>
> I added some additional plugins.
>
> There are still a couple of plugins that I cannot convert because of
> missing functions :
>
> GLW_normalize_topographies
>
>    - Missing LW_norm_topos
>
> GLW_manage_electrodes
>
>    - Missing LW_switch_electrodes
>
> GLW_sumepochs
>
>    - Missing LW_sumepochs
>
> LW_preprocess_data_Nancy
>
>    - Explanations required as to what this function does
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NOCIONS/letswave6/issues/47#issuecomment-164115894>.
>

function [outheader,outdata] = LW_sumepochs(header,data,varargin)
% LW_sumepochs
% Sum epochs
%
% Inputs
% - header : LW5 header
% - data : LW5 data
% - varargin : weightvector
%   Unweighted averaging : 
%   [outheader,outdata]=LW_sumepochs(header,data);
%   Weighted averaging :
%   [outheader,outdata]=LW_sumepochs(header,data,weightvector);
%
% Outputs
% - outheader : LW5 header
% - outdata : LW5 data
%
% Dependencies : none
%
% Author : 
% Talia Retter, modifcation of line 59 of "LW_sumepochs" function by:
% Andr? Mouraux
% Institute of Neurosciences (IONS)
% Universit? catholique de louvain (UCL)
% Belgium
% 
% Contact : andre.mouraux@uclouvain.be
% This function is part of Letswave 5
% See http://nocions.webnode.com/letswave for additional information
%


%determine the weight vector, use ones if not weighted averaging
tp=size(varargin,2);
if (tp>0);
    weight=varargin{1};
else
    weight=ones(size(data,1),1);
end;

%transfer header to outheader
outheader=header;

%add history
i=length(outheader.history)+1;
outheader.history(i).description='LW_sumepochs';
outheader.history(i).date=date;
outheader.history(i).index=varargin;

%change number of epochs
outheader.datasize(1)=1;

%weight
for epochpos=1:size(data,1);
    data(epochpos,:,:,:,:,:)=weight(epochpos)*data(epochpos,:,:,:,:,:);
end;

%average  (Talia: now SUM (was utdata=sum(data,1)/sum(weight);)) 
outdata=sum(data,1); 

%adjust events
if isfield(outheader,'events');
    for i=1:size(outheader.events,2);
        outheader.events(i).epoch=1;
    end;
end;

%adjust conditions
if isfield(outheader,'conditions');
    conditions=outheader.conditions;
    disp('Also averaging conditions across epochs');
    if size(varargin,2)>0;
        disp('WARNING : Applying weights to condition values');
        
    end;
    for conditionpos=1:size(conditions,2);
        conditions(:,conditionpos)=conditions(:,conditionpos)+weight;
    end;
    conditions=squeeze(sum(conditions,1)/sum(weight));
    outheader.conditions=conditions;
end;

%delete dipfit
if isfield(outheader,'fieldtrip_dipfit');
    rmfield(outheader,'fieldtrip_dipfit');
end;

%delete epochdata
if isfield(outheader,'epochdata');
    rmfield(outheader,'epochdata');
end;
        
        
end


function [header_out, data_out] = LW_switch_electrodes(header_in, data_in, flag_bio_to_1020, flag_1020_to_bio)
%
% INPUTS
% - header_in (LW5 header)
% - data_in (LW5 data)
%
% OUTPUTS
% - header_out (LW5 header)
% - data_out (LW5data)
%
% DEPENDENCIES 
% - (none)


% avoid annoying Matlab warnings
warning off MATLAB:xlsread:Mode;

% default electrode location file
location_letswave = which('letswave');
[directory_letswave, n, e] = fileparts(location_letswave);
directory_spherical_location = [directory_letswave '/resources/electrodes/spherical_locations/'];

% load the switching file
dir_current = pwd;
cd(directory_spherical_location);
[num, txt, raw] = xlsread('Biosemi128_ANT1020_match.xls', '', '', 'basic');
cd(dir_current);
column_bio  = 1;
column_1020 = 2;

if(flag_bio_to_1020)
    column_from = column_bio;
    column_to   = column_1020;
    header_in.history(length(header_in.history) +1).description = 'LW_biosemi_to_ANT1020';
    header_in.history(length(header_in.history)).date=date;
elseif(flag_1020_to_bio)
    column_from = column_1020;
    column_to   = column_bio;
    header_in.history(length(header_in.history) +1).description = 'LW_ANT1020_to_biosemi';
    header_in.history(length(header_in.history)).date=date;
end

% switch the labels
for i=1: length(header_in.chanlocs)
    for j=1: length(txt)
        if( strcmpi(header_in.chanlocs(i).labels, txt{j, column_from}) )
            header_in.chanlocs(i).labels = char(txt{j, column_to});
        break;
        end
    end
end

% transfert to output
header_out = header_in;
data_out   = data_in;

end


function [outheader, outdata] = LW_norm_topos(header, data, selectedchannels, normMethod)

%
% Author :
% Corentin Jacques
% Institute of Neurosciences (IONS)
% Universit� catholique de louvain (UCL)
% Belgium
%

%transfer header to outheader
outheader=header;

%add history
i=length(outheader.history)+1;
outheader.history(i).description=['LW_norm_topos_',normMethod];
outheader.history(i).date=date;
outheader.datasize(2) = length(selectedchannels);

outdata = zeros(outheader.datasize);

normMethod = lower(normMethod);


%loop through all the data. 
for epochpos=1:size(data,1)    
        for indexpos=1:size(data,3)
            for dz=1:size(data,4)
                for dy=1:size(data,5);
                    switch normMethod
                        case 'mccarthy & wood'                            
                           scaling =  sqrt(sum(squeeze(data(epochpos,selectedchannels,indexpos,dz,dy,:)).^2,1));
%                            scaling =  sum(abs(squeeze(data(epochpos,selectedchannels,indexpos,dz,dy,:))),1);
                           disp(num2str(scaling));
                           outdata(epochpos,:,indexpos,dz,dy,:) = bsxfun(@rdivide,squeeze(data(epochpos,selectedchannels,indexpos,dz,dy,:)),scaling);
                            
                        case 'z-score';
                            outdata(epochpos,:,indexpos,dz,dy,:) = zscore(squeeze(data(epochpos,selectedchannels,indexpos,dz,dy,:)));
                            
                        otherwise
                            error('unknown normalize method!');                            
                    end
                end
            end
        end
end

**Comment by amouraux** [comment]
Dear Joan,

Typically, what this function does could now be implemented as a script?

Best wishes,
André

**Comment by JoanLS** [comment]
Hi André,

Apologies for the late reply. The LW_preprocess_data_Nancy plugin is useful
for also visualising the triggers so we can easily evaluate the stimulation
sequences. It is also useful to be able to import the Sinstim output to
extract the exact stimulation frequencies and rename the triggers according
to the stimulation conditions.

Perhaps if there were LW6 functions that could do these things we could
bypass the plugin and use scripting instead?

Have a nice day,
Joan
