### ISSUE TITLE
problem in update "readlocs.m"

### ISSUE THREAD

**Issue by hughherald** [NOCIONS/letswave6#48]
Dear Andre,
I notice that you update the "readlocs.m" file in the change of "added CCA and other bug fixes". 
Now it does not work for "edit electrode coordinates". 

"readlocs.m" seems changes a lot. I did not get the main idea. I suppose it is a new version update.

**Comment by amouraux** [comment]
You can put the previous version back. I just tried to fix the problem of someone who was unable to get electrode coordinates… 

Best wishes,
André

**Comment by hughherald** [comment]
It has been done.
