### ISSUE TITLE
error in waveform multiviewer

### ISSUE THREAD

**Issue by Roxanedk** [NOCIONS/letswave6#50]
Hi, 

I updated to the newest version of letswave 6 (NOCIONS-letswave6-9de1d8a), however, the waveform multiviewer doesn't seem to work anymore and gives me the following error: 

Error using hg.figure/set
The name 'SizeChangedFcn' is not an accessible property for an instance of class 'figure'.

Error in CGLW_multi_viewer/CGLW_my_view_OpeningFcn (line 549)
            set(handles.fig1,'SizeChangedFcn',@fig1_SizeChangedFcn);

Error in CGLW_multi_viewer (line 20)
CGLW_my_view_OpeningFcn;

Error in letswave_gui>proc_multi_viewer_Callback (line 1019)

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in letswave_gui (line 34)

Error in @(hObject,eventdata)letswave_gui('proc_multi_viewer_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating uimenu Callback

Thanks,

**Comment by hughherald** [comment]
Thanks very much for show me the issue. 
Now it is fixed.

It is the version problem of matlab.
SizeChangedFcn for figure is only supported by 2014b or after.
Before we can only use resizefcn, more details can be see from
http://nl.mathworks.com/help/matlab/graphics_transition/why-has-the-behavior-of-resizefcn-changed.html?searchHighlight=resizefcn
