### ISSUE TITLE
head plot in SSEP scalp map

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#52]
The 2D plot works perfectly in the SSEP scalp map, but even after spline headmodel the 3D plot gives this back

Undefined function 'chanlocs' for input arguments of type 'double'.

Error in GLW_figure_scalpmap_SSEP_series>headplot_btn_Callback (line 608)
        chanlocs2=chanlocs(1);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in GLW_figure_scalpmap_SSEP_series (line 24)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)GLW_figure_scalpmap_SSEP_series('headplot_btn_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uicontrol Callback

**Comment by amouraux** [comment]
Fixed!
