### ISSUE TITLE
problems in the CLW_save.m

### ISSUE THREAD

**Issue by hughherald** [NOCIONS/letswave6#53]
in the latest updating 3c3d8c4 fixed bug in CWT

I see some codes like 
"<<<<<<< Updated upstream"
">>>>>>> Stashed changes"

It could not be understand by matlab, make errors in saving data.
What these codes are?

**Comment by amouraux** [comment]
Fixed. I wonder how this file got corrupted??

**Comment by hughherald** [comment]
Me too.
Do you using some special tools for edit the codes?
Or some bugs in github during uploading.

Gan
