### ISSUE TITLE
Find peaks in waveforms

### ISSUE THREAD

**Issue by ajankovski** [NOCIONS/letswave6#54]
Check "event" creation process

**Comment by hughherald** [comment]
In the dialogue "Find peaks in waveforms", there is some bugs when the events in the head is empty.
I try to fix it. It runs well on Aleksandar's computer, but still not sure.
And some codes are still in the style of Matlab 2015 which make it unable to run in Matlab 2012.

**Comment by amouraux** [comment]
Should be fixed now, hopefully! This function is a big mess...
