### ISSUE TITLE
"ok" peaks in waveform

### ISSUE THREAD

**Issue by ajankovski** [NOCIONS/letswave6#55]
this message appears when I press OK after I created a new event

Saving : G:\data\ajankovski\ESpG\PEAKS PCA ESpG\TEST-EVENT merged_epochs avg 001-100 AVG-LatSPIN-SPIN bl art-sup dcld PCA comp08 ESpG Low MED
Error using CLW_save_header
Too many input arguments.

Error in GLW_find_peaks>process_btn_Callback (line 317)
    CLW_save_header(filename,[],header);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in GLW_find_peaks (line 24)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)GLW_find_peaks('process_btn_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uicontrol Callback

>>

**Comment by amouraux** [comment]
Fixed!
