### ISSUE TITLE
Incorrect bins for segmentation by events

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#63]
Hi André,

I noticed that when segmenting by events, the output file is 1 bin off from the number of bins I had specified, resulting in a different frequency resolution for the FFT. Could this be a rounding issue due to the segmentation function taking the epoch duration instead of the precise n° of bins?

Thank you in advance!
Joan
![lw6_pbsegmentation](https://cloud.githubusercontent.com/assets/15615825/12728276/4f541926-c921-11e5-9116-3a98788ab2ce.png)

**Comment by amouraux** [comment]
This should also have been fixed in the latest update.
