### ISSUE TITLE
Chunking in successive epochs

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#66]
Hi André,

Would it be possible to restore the option to define the number of epochs to be chunked (see LW5 window)? 

Thanks!
Joan
![lw6_chunkingoption](https://cloud.githubusercontent.com/assets/15615825/13434069/e49e2ab6-dfd4-11e5-8472-77278039d7ac.png)

**Comment by amouraux** [comment]
Done! The option should appear after updating...
