### ISSUE TITLE
Crop signals functions

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#67]
Hi André,

I'm really enjoying the current version of Lets6! :-)

This one is a minor issue: sometimes the crop signals interface does not produce any output, it seems freezed. Once relaunched then gives the output.
I run it on matlab 2012 and win 10 but also on matlab 2014 and win 10. 

Best,
e

**Comment by amouraux** [comment]
Strange. No error message?

**Comment by EVale** [comment]
I TRIED AGAIN.
it worked fine (it does work fine) but it seems that if the interface is kind of left too long on screen then this no-output-whatsoever happens. And no error message either.
EEGLAB is concurrently open but I don't see why should bother letsw...
