### ISSUE TITLE
Issue with FFT Notch filter

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#69]
Hi André,

I noticed that there was a problem with the FFT multinotch filter. The filter is not centred on the desired frequency & harmonics (e.g. 12 Hz) but systematically shifted by one bin above. This was especially apparent in my data because I had a very coarse frequency resolution and was filtering a single bin.
 
In the code, I have replaced the following lines in ILW_buildFFTbandpass.m:

_dx1=fix(((locutoff-header.xstart)/header.xstep)+1);
dx2=fix(((hicutoff-header.xstart)/header.xstep)+1);_

with

_**dx1=round(((locutoff-header.xstart)/header.xstep));
dx2=round(((hicutoff-header.xstart)/header.xstep));**_

This appears to have fixed the problem (see screencap below). 

The problem is also applicable for LW5 since it uses the same script.
![lw6_pbnotch](https://cloud.githubusercontent.com/assets/15615825/13463400/59b123c8-e08c-11e5-8fed-9548ce4769a9.png)

**Comment by amouraux** [comment]
Thanks Joan!
I just added your correction to the distribution.

I also modified the notch filter function. It is now also possible to invert the filter, such as to keep only a set of frequencies. This should be useful for time-domain analysis of SSEPs.
