### ISSUE TITLE
Find peaks in waveforms

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#71]
![image](https://cloud.githubusercontent.com/assets/11717558/13534161/b86d41f8-e22b-11e5-8abf-ad34f6461bfa.png)

It does not seem to display well the function.
Same it seems to apply to explore interval in multiviewer average.

![image](https://cloud.githubusercontent.com/assets/11717558/13534277/360cb350-e22c-11e5-8875-c21d7afc58db.png)

In addition, it seems I get different values when I ask for max value in ROI generator compared with multiviewer. I will further check and let you know if that is a recursive phenomenon.

**Comment by amouraux** [comment]
Display problem should now be fixed.
Can you confirm the problem with the max values obtained in ROI generator vs. multi viewer?

**Comment by EVale** [comment]
Here is the display I get after the last update
![image](https://cloud.githubusercontent.com/assets/11717558/14150259/24056962-f6a0-11e5-8f04-34fbb370cb7f.png)

Therefore, I could not extract the data.

**Comment by EVale** [comment]
Hi!
I get the following error with the last update:

??? Error while evaluating uicontrol Callback

??? Undefined function or variable "table_data".

Error in ==> GLW_explore_ROI>process_btn_Callback at 465
uitable(h,'Data',table_data,'ColumnName',colheaders,'Units','normalized','Position', [0 0 1 1]);

Error in ==> gui_mainfcn at 96
        feval(varargin{:});

Error in ==> GLW_explore_ROI at 24
    gui_mainfcn(gui_State, varargin{:});

Error in ==> @(hObject,eventdata)GLW_explore_ROI('process_btn_Callback',hObject,eventdata,guidata(hObject))

![image](https://cloud.githubusercontent.com/assets/11717558/16601677/22badde6-4306-11e6-996b-957dc3f1b01b.png)
