### ISSUE TITLE
Pool channels - incorrect naming

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#74]
Hi André,

The average channels function does not seem to take into account the new name for the averaged channels when I am not adding it to the original channels. Everything works fine when all the channels are kept. 

Thanks in advance
![lw6_pbpoolchannels](https://cloud.githubusercontent.com/assets/15615825/14136143/94040d70-f661-11e5-871e-c7e52ed5649d.png)
!
Joan

**Comment by amouraux** [comment]
Fixed! Thank you for spotting and reporting this.
