### ISSUE TITLE
Compute mean amplitude / area under curve?

### ISSUE THREAD

**Issue by JoanLS** [NOCIONS/letswave6#75]
Hi André,

Is it there a possibility with the current LW6 version to compute the mean amplitude or area under the curve for time-domain data? I have tried to average time-points with the sliding window but that doesn't seem very optimal... What would be nice is to be able to set multiple custom ranges (e.g. 0.25 - 0.28, 0.35 - 0.40) and compute the values. I am currently doing it via Matlab, but it is then not easy to revisualise the data via the multiviewer or plot topographies. 

Thanks a lot!
Joan

**Comment by amouraux** [comment]
Not for now. 
In LW7, scripting and working directly in Matlab is much easier...
