### ISSUE TITLE
T_test figure creation

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#79]
Hi Andre,

there seems to be a problem in calling figure creation with t-test files

Error using isfield
Not enough input arguments.

Error in GLW_figure_waveforms>update_listbox (line 129)
    if isfield(dataset.header.index_labels);

Error in GLW_figure_waveforms_GLW_figure_waveforms_OpeningFcn (line 76)
update_listbox(handles);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in GLW_figure_waveforms (line 22)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in LW_figure_waveforms (line 79)
        [a out_configuration]=GLW_figure_waveforms('dummy',configuration,datasets);

Error in letswave_gui>menu_callback (line 329)

Not sure whether this can be due to the several indexes within the file...any idea?

Cheers,

elia

**Comment by amouraux** [comment]
Fixed.
