### ISSUE TITLE
the value of "alpha level" in the statistic test is useless

### ISSUE THREAD

**Issue by hughherald** [NOCIONS/letswave6#80]
Dear Andre,
Recently, I'm checking the ttest and ANOVA function in letswave. I found the value of "alpha level" actually is not used in the computation. The result will not changed with different alpha level value.
Is it true?

Gan

**Comment by amouraux** [comment]
Dear Gan,

Are you sure?
the alpha level is only used for the cluster-based permutation and, looking at the code, it does seem that the alpha value is used…

Best wishes,
André

**Comment by flamancini** [comment]
It does work for me..

On 13 Apr 2016, at 08:32, Andr? Mouraux <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Gan,

Are you sure?
the alpha level is only used for the cluster-based permutation and, looking at the code, it does seem that the alpha value is used...

Best wishes,
Andr?

> On 12 Apr 2016, at 10:06, Gan Huang <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Dear Andre,
> Recently, I'm checking the ttest and ANOVA function in letswave. I found the value of "alpha level" actually is not used in the computation. The result will not changed with different alpha level value.
> Is it true?
>
> Gan
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/NOCIONS/letswave6/issues/80>


-

**Comment by hughherald** [comment]
Dear Andre,
Yes, you are right. I find it does not use for t-test or ANOVA. But I'm not check it for permutation test.
