### ISSUE TITLE
Labels are not the same in  ICA assign matrix.

### ISSUE THREAD

**Issue by hughherald** [NOCIONS/letswave6#9]
[GLW_ICA_apply_filter.m line 123]  case 'LW_ICA_assign'
[LW_ICA_assign_matrix.m]              gui_info.function_name='LW_ICA_assign_matrix';

which makes the assigned files could not be open.
The error shows "ERROR : no matrix found in dataset".

I'm not sure there labels are used in somewhere else, so not fixed yet.

**Comment by amouraux** [comment]
Dear Gan,

Just fixed the mistake.
The error was also present in other functions.
