### ISSUE TITLE
Visualisation issues on Windows

### ISSUE THREAD

**Issue by cedlenoir** [NOCIONS/letswave6#98]
There are still some visualisation issues on Windows with the GLW_import_(type of files)

**Comment by cedlenoir** [comment]
the same issue occurs for artefact rejection, it is solved when "normalized" is chosen for Units in the GUI

**Comment by amouraux** [comment]
Fixed in the artefact rejection function. But, I cannot replicate it in the GLW_import functions?

**Comment by cedlenoir** [comment]
I adjust the window and moved the items in "characters" units and then choose "normalized" and it works.
